// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIc9ovWIk5XzmRZLFk-E0uVI8ai_0Dxrk',
    appId: '1:1069702307492:web:e817b1d97057920fead031',
    messagingSenderId: '1069702307492',
    projectId: 'softfocus-flutter',
    authDomain: 'softfocus-flutter.firebaseapp.com',
    storageBucket: 'softfocus-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu8AXMHSqPFsg6h9HKugtzrbRcqIuZpE',
    appId: '1:1069702307492:android:91cc6aa808e33a89ead031',
    messagingSenderId: '1069702307492',
    projectId: 'softfocus-flutter',
    storageBucket: 'softfocus-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvCgcdqm4ZkRHNSHN2QIwe8dhhmAcEtHI',
    appId: '1:1069702307492:ios:4c1e48f85306883fead031',
    messagingSenderId: '1069702307492',
    projectId: 'softfocus-flutter',
    storageBucket: 'softfocus-flutter.firebasestorage.app',
    iosBundleId: 'com.softfocus.flutterAppSoftfocus',
  );
}
